# Generated by Django 4.1.1 on 2022-09-20 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0002_post_likes"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="snippet",
            field=models.CharField(
                default="Click Link above to Read Blog Post... ", max_length=255
            ),
        ),
    ]
