# Generated by Django 4.1.1 on 2022-09-22 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0007_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="body",
            field=models.TextField(blank=True, null=True),
        ),
    ]
